# Generated by Django 5.2.3 on 2025-06-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentralMonitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('plantao', models.CharField(max_length=100)),
                ('base', models.CharField(max_length=100)),
                ('total_veiculos', models.IntegerField()),
                ('veiculos_pernoite', models.IntegerField()),
                ('veiculos_viagem', models.IntegerField()),
                ('veiculos_manutencao', models.IntegerField()),
                ('veiculos_cliente', models.IntegerField()),
                ('tentativas_roubo', models.IntegerField()),
                ('roubos_consolidados', models.IntegerField()),
                ('acidentes', models.IntegerField()),
                ('desvios_rota', models.IntegerField()),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'centralMonitoramento',
            },
        ),
        migrations.CreateModel(
            name='PassagemPlantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('plantao', models.CharField(max_length=100)),
                ('base', models.CharField(max_length=100)),
                ('total_veiculos', models.IntegerField()),
                ('veiculos_pernoite', models.IntegerField()),
                ('veiculos_viagem', models.IntegerField()),
                ('veiculos_manutencao', models.IntegerField()),
                ('veiculos_cliente', models.IntegerField()),
                ('tentativas_roubo', models.IntegerField()),
                ('roubos_consolidados', models.IntegerField()),
                ('acidentes', models.IntegerField()),
                ('desvios_rota', models.IntegerField()),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
    ]
