# Generated by Django 5.2.3 on 2025-06-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_centralmonitoramento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralmonitoramento',
            name='usuario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
