# Generated by Django 5.2.3 on 2025-06-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_alter_centralmonitoramento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralmonitoramento',
            name='parada_nao_autorizada',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='centralmonitoramento',
            name='perda_sinal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='centralmonitoramento',
            name='rotas_embarcadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='centralmonitoramento',
            name='rotas_embarcadas_3s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='centralmonitoramento',
            name='rotas_embarcadas_t4s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='centralmonitoramento',
            name='sinistros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='centralmonitoramento',
            name='tem_carregador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='centralmonitoramento',
            name='tem_descanso_pe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='centralmonitoramento',
            name='tem_mouse_pad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='centralmonitoramento',
            name='veiculos_abandonados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='centralmonitoramento',
            name='veiculos_bloqueados_inatividade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='centralmonitoramento',
            name='veiculos_borracharias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='centralmonitoramento',
            name='veiculos_para_iniciar_viagem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='centralmonitoramento',
            name='veiculos_postos_fiscais',
            field=models.IntegerField(default=0),
        ),
    ]
