# Generated by Django 5.2.2 on 2025-06-16 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_centralmonitoramento_parada_nao_autorizada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centralmonitoramento',
            name='acidentes',
        ),
        migrations.RemoveField(
            model_name='centralmonitoramento',
            name='roubos_consolidados',
        ),
        migrations.RemoveField(
            model_name='centralmonitoramento',
            name='tentativas_roubo',
        ),
    ]
