# Generated by Django 5.2.2 on 2025-06-16 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_remove_centralmonitoramento_acidentes_and_more'),
    ]

    operations = [
    ]
