# Generated by Django 5.2.2 on 2025-06-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_auto_20250615_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralmonitoramento',
            name='nome_backoffice',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='centralmonitoramento',
            name='nome_usuario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
