# Generated by Django 5.2.3 on 2025-07-25 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_centralmonitoramento_nome_backoffice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassageCFTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('operador', models.CharField(max_length=100)),
                ('base', models.CharField(max_length=100)),
                ('nome_backoffice', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='centralmonitoramento',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
