# Generated by Django 5.2.3 on 2025-07-28 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_passagecftv_centralmonitoramento_data_envio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centralmonitoramento',
            old_name='nome_backoffice',
            new_name='nome_coordenador',
        ),
    ]
